

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  equipment_name text not null,
  category text not null,
  asset_code text unique not null,
  condition text default 'Good' check (condition in ('Good','Fair','For Repair')),
  availability text default 'Available' check (availability in ('Available','Borrowed')),
  created_at timestamptz default now()
);

create table if not exists public.borrow_transactions (
  id bigint generated by default as identity primary key,
  equipment_id bigint references public.equipment(id),
  borrower_name text not null,
  borrower_type text not null check (borrower_type in ('Student','Faculty','Staff')),
  department text not null,
  date_borrowed date default current_date,
  due_date date not null,
  date_returned date,
  status text default 'Borrowed' check (status in ('Borrowed','Returned','Overdue')),
  user_id uuid references auth.users(id),
  created_at timestamptz default now(),
  check (due_date >= date_borrowed)
);

create index if not exists idx_borrow_transactions_equipment_id
  on public.borrow_transactions(equipment_id);

create index if not exists idx_borrow_transactions_status
  on public.borrow_transactions(status);

alter table public.equipment enable row level security;
alter table public.borrow_transactions enable row level security;

drop policy if exists "Authenticated users can view equipment" on public.equipment;
create policy "Authenticated users can view equipment"
on public.equipment for select to authenticated using (true);

drop policy if exists "Authenticated users can insert equipment" on public.equipment;
create policy "Authenticated users can insert equipment"
on public.equipment for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update equipment" on public.equipment;
create policy "Authenticated users can update equipment"
on public.equipment for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete equipment" on public.equipment;
create policy "Authenticated users can delete equipment"
on public.equipment for delete to authenticated using (true);

drop policy if exists "Authenticated users can view transactions" on public.borrow_transactions;
create policy "Authenticated users can view transactions"
on public.borrow_transactions for select to authenticated using (true);

drop policy if exists "Authenticated users can insert transactions" on public.borrow_transactions;
create policy "Authenticated users can insert transactions"
on public.borrow_transactions for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Authenticated users can update transactions" on public.borrow_transactions;
create policy "Authenticated users can update transactions"
on public.borrow_transactions for update to authenticated
using (true) with check (true);

drop policy if exists "Authenticated users can delete transactions" on public.borrow_transactions;
create policy "Authenticated users can delete transactions"
on public.borrow_transactions for delete to authenticated using (true);

-- Optional sample data for demonstration:
insert into public.equipment (equipment_name, category, asset_code, condition, availability)
values
('Epson Projector','Projector','PROJ-001','Good','Available'),
('Acer Laptop','Laptop','LAP-002','Good','Available'),
('Canon Camera','Camera','CAM-001','Fair','Available')
on conflict (asset_code) do nothing;
